### ISSUE TITLE
Document how to write a very basic e2e test in the repository

### ISSUE THREAD

**Issue by mdelapenya** [elastic/e2e-testing#1237] opened 2021-06-07 15:53 UTC
We'd like to speed up the process of starting with the project and writing a test scenario that passes.

**Comment by cachedout** [comment] 2021-07-30 14:48
Hi @mdelapenya . I think this may now be a duplicate of https://github.com/elastic/observability-robots/issues/608

Do you want to keep them both open or just go ahead and close this one?

**Comment by mdelapenya** [comment] 2021-08-02 06:10
I'd keep both, as the robots one is related to the E2E strategy/vision, and this one is related to specifically this test framework

**Closed** 2021-08-03 16:02 UTC
Labels: Team:Automation, area:documentation, area:test, priority:medium, size:M, triaged
