### ISSUE TITLE
8.0 branch is scheduled although their artifacts are not existing in the endpoint

### ISSUE THREAD

**Issue by mdelapenya** [elastic/e2e-testing#2515] opened 2022-05-11 05:57 UTC
Build URL: https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/8.0/849/pipeline

cc/ @v1v

**Comment by v1v** [comment] 2022-05-11 08:25
I'm a bit confused, the daily run uses `8-minor-1` as per https://github.com/elastic/e2e-testing/blob/main/.ci/schedule-daily.groovy#L23

`8-minor-1` is dynamically transformed in https://github.com/elastic/apm-pipeline-library/blob/842b54bf9d7e14bdd8be6ccb3d2368157c6bf013/vars/getBranchesFromAliases.groovy#L45-L48


and `current_8 = 8.2.0` as per https://github.com/elastic/apm-pipeline-library/blob/842b54bf9d7e14bdd8be6ccb3d2368157c6bf013/resources/versions/releases.properties#L5

So, I need to find how the `8.0` is calculated

**Comment by v1v** [comment] 2022-05-11 09:54
I cannot reproduce it locally, see https://github.com/elastic/apm-pipeline-library/pull/1684/files#diff-a565e140e1a9d9d08983ce83490a60a61e2f752791da669c87f9b72ab1a569acR85-R88

:/

**Comment by v1v** [comment] 2022-05-11 09:56
Aha 

https://github.com/elastic/e2e-testing/blob/main/.ci/schedule-daily.groovy#L1

so it should use `main` since release versions are merged to main in the apm-pipeline-library but we release manually instead

**Closed** 2022-05-11 16:40 UTC
Labels: area:ci
