### ISSUE TITLE
[Fleet] validate that all packages can be installed

### ISSUE THREAD

**Issue by mdelapenya** [elastic/e2e-testing#134] opened 2020-06-10 16:23 UTC
An additional test (for later) that I do in this PR here is to validate if all the available packages can be installed: https://github.com/elastic/package-storage/pull/54/files#diff-6a13f5c76026f2845117497754dc63e1R95

_Originally posted by @ruflin in https://github.com/elastic/e2e-testing/pull/132#issuecomment-641869853_

**Comment by EricDavisX** [comment] 2020-08-28 14:56
We have the example Fleet + Go implementation code now to access the various packages listed in Ingest Manager.  we could loop thru, like the other noted test and install them, but I'm not sure of the intention here.

 - if the intention to *just see that they install from the stack side and their 'assets' go into ES successfully?  This test is already done on the package side, as noted so the value is quite low.

 - but if is the intention to see each Integration 'deployed' to an Agent policy set on a host thats more interesting and has new challenges and questions
  - the challenge with this is that we can't truly integrate successfully, fully, unless the integration specific software is running on the host (i.e. you can't test Nginx logs writing, if Nginx isn't running on the host).

So, we do have docker images for many of the Integrations.  But if we go that far, we need to include @ycombinator who is working an entire test project (that may make use of e2e testing, but may not in the end).

**Comment by ycombinator** [comment] 2020-08-31 10:56
My current thinking is that any **generic** workflow tests around ingest management should be defined in the `e2e-testing` repository and run using the runner provided in the repository. Of course, if that means installing a single package or two as part of such testing, that's fine. 

However, any **per-package** tests should be defined along with the package itself and run using the `elastic-package` tool. This is because individual package authors will spend most of their time working within their package folders and using the `elastic-package` tool to interact with these packages. So from a developer experience perspective, IMO it would be best for package authors if they could define tests for their packages in the same place where they define their packages and use the same tool (`elastic-package`) that they would use for other package-related needs.

**Comment by mdelapenya** [comment] 2020-08-31 11:56
I totally agree with @ycombinator: the "unit" tests must live along-side the package code. I say unit because they are focused in the package itself.

The e2e repo should cover the high level use cases, not the internal ones

**Comment by EricDavisX** [comment] 2020-09-18 22:55
that's helpful.  Also, I'm thinking further from my original note that this test is called from various repos (or will be) and so it may be helpful to have the generic 'all packages assets' can be installed tests.  And I love that we're planning on putting more package detail oriented tests along with the packages.  I think the System package (and Endpoint) may be the exception... tho they need not be.  I do however intend to help contribute more on both of those as possible.

**Comment by mdelapenya** [comment] 2021-04-28 07:56
I think we can close this issue, as unit testing efforts exists per package in the integrations and elastic-package repository. For e2e tests, we do have scenarios for installing integrations, so maybe we can create separate issues for adding e2e tests for them.

@EricDavisX please close this one if you agree, thanks!

**Comment by EricDavisX** [comment] 2021-04-28 13:08
@ycombinator if you feel the Integrations are managed well enough on the Integrations and Storage side in terms of end to end tests, I am ok to close this.  Unless @ruflin or @ph can cite a risk that is not planned to be mitigated except through a CI usage with this e2e-testing repo?

**Comment by ph** [comment] 2021-04-28 13:37
I am ok to only have the test in the integration repository. cc @jen-huang

**Closed by ph** 2021-04-28 13:37 UTC
Labels: Team:Agent, area:test, triaged

**Comment by ruflin** [comment] 2021-04-28 18:24
I think we are covered with the integrations and package-storage testing but also pinging @mtojek for confirmation.

**Comment by mtojek** [comment] 2021-04-28 18:30
Confirmed. This is already part of integration testing. For reference: https://github.com/elastic/elastic-package/blob/master/docs/howto/asset_testing.md
