### ISSUE TITLE
Testing support for German localised language versions of Microsoft Windows for the Elastic Stack

### ISSUE THREAD

**Issue by jstrassb** [elastic/e2e-testing#2805] opened 2022-07-15 12:06 UTC
I noticed various reports of issues with the installation and ongoing operation of the Elastic Agent on a localised operating system version, specifically German language Microsoft Windows, and was directed here to start a discussion around options to include this in our tests for the Elastic Stack.

The language of Windows changes certain parameters which can lead to problems, e.g. the `Administrator` group name is localised (https://github.com/elastic/beats/pull/26665#issuecomment-879997941 and https://github.com/elastic/beats/pull/26665#issuecomment-882557947).

This leads to known issues for certain components of the Elastic Stack, e.g. Elastic Agent (https://github.com/elastic/elastic-agent/issues/150), and so far we are mostly reactive on reports of such problems.

I would like to suggest include localised testing support for German language Windows in this instance and am opening this issue to discuss further.
Ideally we could extend this to other commonly used localised language versions as well in the future.

**Comment by mdelapenya** [comment] 2022-07-18 10:35
Hey @jstrassb thanks for opening this issue. As a user with two `ñ` in my surname, I think that testing with different language profiles is important: i.e, I'm not `Pena Pena` nor `Pe/a Pe/a` nor `Penya Penya`... 🤣 

What I'm not sure is about the need for an automated test here. I'd advocate for including this kind of verification in the manual test executions that @dikshachauhan-qasource and her team are running apart from the automated tests.

@jlind23 could you help here to identify and prioritise the work here?

**Comment by jlind23** [comment] 2022-07-18 15:57
@mdelapenya i'll bring that up with @deepikakeshav-qasource during our next meeting.

**Comment by dikshachauhan-qasource** [comment] 2022-07-19 04:00
Sure, @jlind23 , We will add this to our meeting items. We are already taking take for French, Korean and Spanish VMs.

**Comment by jstrassb** [comment] 2022-07-21 15:32
@mdelapenya as someone with an `ß` in his surname, that I only substitute as per the rules with double `s`, I completely feel you 😆 

Thanks a lot @dikshachauhan-qasource for looking into this! 
Here specifically my user confirmed that many of the issues they saw with Elastic Agent in a German Windows installation do not appear on an English Windows test system.

**Comment by sachin-frayne** [comment] 2022-07-27 08:05
Hello Team,

I have taken over the case from Janko, can I get an update on this SDH. What are the next steps, should we open an ER give them the number and close out the SDH and the case?

**Comment by ckauf** [comment] 2022-07-28 07:40
> should we open an ER give them the number and close out the SDH and the case?

Hey, I think before we do anything in that direction we need to clarify which OS versions we officially support.  Going back to the customer (BSI / German Federal Office for Information Security) and telling them we are not supporting German OS and we can create an Enhancement Request will surely end in disaster

**Comment by crisdarocha** [comment] 2022-08-01 14:00
@ckauf fully agree that "your language is not supported" will not end well.

@jlind23, @dikshachauhan-qasource and @mdelapenya what is the status here? How did the discussion go in the last meeting?

Thanks!

**Comment by crisdarocha** [comment] 2022-08-02 13:59
Looked into their diagnostics and couldn't find anything useful to help move here.

But it seems the diagnostics itself has the same error message
```
Error 1: unable to gather diagnostics data: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing open \\\\.\\pipe\\elastic-agent-system: Zugriff verweigert"
Error 2: unable to gather metrics data: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing open \\\\.\\pipe\\elastic-agent-system: Zugriff verweigert"
```

I see https://github.com/elastic/elastic-agent/issues/150 catching up some pace. Are we also testing this for German, or is this "candidate 8.5" only for French?

**Comment by crisdarocha** [comment] 2022-08-04 10:15
Could easily reproduce the issue in a Windows 10 in German. Opened a public bug report, so I can give it to the user for their tracking (https://github.com/elastic/elastic-agent/issues/857).

@jlind23 @dikshachauhan-qasource @mdelapenya what do we need to get traction for this bug? Rather large and strategic customer for our public sector in Germany and Europe.

CC: @ckauf @jstrassb

**Comment by mdelapenya** [comment] 2022-08-04 11:35
I don't know if this public repo is the best place to track the issue, as the repo is intended to manage the e2e scenarios that cover Fleet and other different Observability projects: bugs in the scenarios, new scenario request, new platform support, etc.

As the issue described here is related to the elastic-agent, I'd move the ticket to that repo, as a bug: `Localised language versions of MS Windows fails with XYZ error`

**Comment by crisdarocha** [comment] 2022-08-04 11:39
@mdelapenya I agree with you. 

I created https://github.com/elastic/elastic-agent/issues/857 with that intent. Focusing on the bug itself and getting it solved in a sustainable way as soon as possible.

**Comment by crisdarocha** [comment] 2022-08-04 11:54
@mdelapenya as we have the issue tracked in the other repo, feel free to close this one, if you prefer.

Thanks a lot!

**Closed** 2022-08-04 11:57 UTC
