### ISSUE TITLE
E2E create-stack fails as of October 24, 2022

### ISSUE THREAD

**Issue by aleksmaus** [elastic/e2e-testing#3159] opened 2022-10-24 20:09 UTC
Trying to spin up the stack for E2e, following the instructions, getting fleet server setup failure.

Observed:
1. Elasicsearch and kibana are set up. Kibana is accessible is on HTTP port (not HTTPS)
2. Fleet server setup failed, not running.
<img width="2249" alt="Screen Shot 2022-10-24 at 4 07 20 PM" src="https://user-images.githubusercontent.com/872351/197618997-eb101d33-2218-4be0-b8b9-2c3d96543be0.png">

3. Navigating to the fleet-server setup page with 8.6.0 stack give UI validation error because the url can't be HTTP
<img width="1260" alt="Screen Shot 2022-10-24 at 3 36 38 PM" src="https://user-images.githubusercontent.com/872351/197618969-8e508180-c895-4094-8529-2f5316958d76.png">

Need to be able to test the agent install/uninstall with Endpoint service against 8.6.0 stack.
Please advice what is the best way to proceeed.

**Comment by cmacknz** [comment] 2022-10-25 18:16
@AndersonQ have you seen this in other tests?

**Comment by AndersonQ** [comment] 2022-10-25 18:37
yes, I've managed to reproduce it today. However I haven't been able yet to pin point the problem. So far I found the agent docker container fails first because _"License is not available"_, then it seems to be using wrong credentials: _"unable to authenticate with provided credentials and anonymous access is not allowed for this request"_

The last error `unable to authenticate with provided credentials and anonymous access is not allowed for this request` keeping being repeated until the container exits. I believe it keeps trying until a timeout is reached. However as I said, I haven't had the time to pinpoint the root cause yet.

```
Kibana Fleet setup failed: http POST request to http://3.142.220.142:5601/api/fleet/setup fails: fail to execute the HTTP POST request: Post "http://3.142.220.142:5601/api/fleet/setup": read tcp 172.18.0.4:45186->3.142.220.142:5601: read: connection reset by peer. Response: 
Kibana Fleet setup failed: http POST request to http://3.142.220.142:5601/api/fleet/setup fails: fail to execute the HTTP POST request: Post "http://3.142.220.142:5601/api/fleet/setup": dial tcp 3.142.220.142:5601: connect: connection refused. Response: 
Kibana Fleet setup failed: http POST request to http://3.142.220.142:5601/api/fleet/setup fails: License is not available.: %!w(<nil>). Response: {"statusCode":503,"error":"Service Unavailable","message":"License is not available."}
Kibana Fleet setup failed: http POST request to http://3.142.220.142:5601/api/fleet/setup fails: [security_exception: [security_exception] Reason: unable to authenticate with provided credentials and anonymous access is not allowed for this request]: unable to authenticate with provided credentials and anonymous access is not allowed for this request: %!w(<nil>). Response: {"statusCode":401,"error":"Unauthorized","message":"[security_exception: [security_exception] Reason: unable to authenticate with provided credentials and anonymous access is not allowed for this request]: unable to authenticate with provided credent... (truncated)
```

**Comment by cmacknz** [comment] 2022-10-25 18:47
Thanks @AndersonQ, I assigned this to you to drive forward as part of the general effort to fix the E2E tests. 

@cachedout is there anyone who understands the internals of how the E2E tests are provisioned that could help us investigate this?

**Comment by cachedout** [comment] 2022-10-25 19:10
@cmacknz Yes of course. Please have @AndersonQ sync up with @pazone

**Comment by pazone** [comment] 2022-10-26 16:09
We can start with changing the `FLEET_URL` [here](https://github.com/elastic/e2e-testing/blob/main/.ci/ansible/tasks/setup_test_script.yml#L59) for 8.6 branch

**Comment by AndersonQ** [comment] 2022-10-27 09:50
hi, @pazone,
Sorry, but I did not quite get what you're suggesting to change, you meant to change the `FLEET_URL` to use HTTPS instead?

**Comment by pazone** [comment] 2022-10-27 16:28
@AndersonQ yes. Seems like it is specified there.

**Comment by AndersonQ** [comment] 2022-10-28 14:12
I found out a workaround, I don't know yet the root cause, but [recreating the stack](https://github.com/elastic/e2e-testing/blob/main/e2e/TROUBLESHOOTING.md#the-stack-vm) fixes it.

Given the idea of recreating the stack is to fix a API token expired, I can only conclude the API token is expired/invalid since the beginning.

**Comment by kuisathaverat** [comment] 2022-12-30 09:43
resolved at https://github.com/elastic/e2e-testing/pull/3285

**Closed by kuisathaverat** 2022-12-30 09:43 UTC
Labels: enhancement
